name: brotli
description: Pure Dart Brotli decoder.
version: 0.4.0
homepage: https://github.com/tiagohm/brotli

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.8
  effective_dart: ^1.3.1
