name: brotli
description: Pure Dart Brotli decoder.
version: 0.6.0
homepage: https://github.com/tiagohm/brotli

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  test: ^1.24.2
  lints: ^2.0.1
