name: brotli
description: Brotli Decoder for Dart.
version: 0.1.0
homepage: https://github.com/tiagohm/brotli
author: tiagohm <tiago.henrique.cco@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dev_dependencies:
  test: ^1.6.0
  effective_dart: ^1.1.2
