name: brotli
description: Pure Dart Brotli decoder.
version: 0.5.0
homepage: https://github.com/tiagohm/brotli

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  test: ^1.16.8
  lints: ^2.0.1
