name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Dark SDK
        uses: dart-lang/setup-dart@v1

      - name: Pub Get
        run: dart pub get

      - name: Test
        run: dart test
